### ISSUE TITLE
SIGABORT on some .Z files

### ISSUE THREAD

**Issue by malespiaut** [wfr/unshieldv3#6] opened 2022-05-08 19:12 UTC
Hello,

I've compiled the latest git revision of your project to try to extract a .Z file, but I got a SIGABORT in return.

```
$ md5sum DATA.Z
0d08bf534d689c8f9c074e98232097dd  DATA.Z
```

```
$ unshieldv3 list -v DATA.Z
Path                      Size  Date
----                      ----  ----
Data\CHAMPB01.BPT         1202  1997-04-29 15:21:24
Data\CHAMPA01.BPT          450  1997-04-29 15:21:02
Data\CHAMPC01.BPT         1202  1997-04-29 15:21:30
Data\ILE10.BKF         5530969  1997-04-23 17:12:50
Data\LIST01.BPT            338  1997-04-29 15:20:58
Data\ILE11.BKF         5549372  1997-04-23 17:12:54
Data\ile10\ile10.trk   1790030  1997-04-02 15:47:30
Data\ile11\ile11.trk   1179563  1997-04-01 16:08:22
```

```
$ unshieldv3 extract DATA.Z .
Data\CHAMPB01.BPT
      Compressed size:       1202
terminate called after throwing an instance of 'std::runtime_error'
  what():  Blast decompression error: -1
fish: Job 1, 'unshieldv3' terminated by signal SIGABRT (Abort)
```
[data.z.zip](https://github.com/wfr/unshieldv3/files/8647625/data.z.zip)

This archive contains bonus tracks for the 1997 video game Moto Racer, and was part of a free download by the original developers.

Best regards.

**Comment by wfr** [comment] 2022-05-08 19:33
Thank you for the report. I can reproduce the problem.

**Comment by wfr** [comment] 2022-05-08 20:57
Turns out DATA.Z from Moto Racer is an uncompressed archive, which was not supported properly yet.

Fixed in the master branch:
```
$ ./unshieldv3 extract ./test-data/MotoRacer-DATA.Z /tmp/out/
Data\CHAMPB01.BPT
      Compressed size:       1202
    Uncompressed size:       1202
Data\CHAMPA01.BPT
      Compressed size:        450
    Uncompressed size:        450
Data\CHAMPC01.BPT
      Compressed size:       1202
    Uncompressed size:       1202
Data\ILE10.BKF
      Compressed size:    5530969
    Uncompressed size:    5530969
Data\LIST01.BPT
      Compressed size:        338
    Uncompressed size:        338
Data\ILE11.BKF
      Compressed size:    5549372
    Uncompressed size:    5549372
Data\ile10\ile10.trk
      Compressed size:    1790030
    Uncompressed size:    1790030
Data\ile11\ile11.trk
      Compressed size:    1179563
    Uncompressed size:    1179563
```

**Comment by wfr** [comment] 2022-05-09 08:30
Fixed.

**Closed as completed by wfr** 2022-05-09 08:30 UTC
Labels: bug
